version: 2

models:
  - name: stg_dates_dim
    columns:
      - name: id_date
        tests:
          - not_null
          - unique
      - name: day
      - name: month
      - name: week_nb
      - name: quarter
      - name: year

  - name: stg_insurance_providers_dim
    columns:
      - name: id_insurance_provider
        tests:
          - not_null
          - unique
      - name: name_insurance_provider
        tests:
          - accepted_values:
              values: ['Cigna', 'Medicare', 'Blue Cross', 'UnitedHealthcare', 'Aetna']
              config:
                severity: warn
                warn_if: ">0"

  - name: stg_hospitals_dim
    columns:
      - name: id_hospital
        tests:
          - not_null
          - unique
      - name: name_hospital

  - name: stg_rooms_dim
    columns:
      - name: id_room
        tests:
          - not_null
          - unique
      - name: id_hospital
        tests: 
          - relationships:
              to: ref('stg_hopitals_dim')
              field: id_hospital
      - name: room_number

  - name: stg_doctors_dim
    columns:
      - name: id_doctor
        tests:
          - not_null
          - unique
      - name: name_doctor

  - name: stg_admission_types_dim
    columns:
      - name: id_admission_type
        tests:
          - not_null
          - unique
      - name: admission_type
        tests:
          - accepted_values:
              values: ['Urgent', 'Emergency', 'Elective']

  - name: stg_treatments_dim
    columns:
      - name: id_treatment
        tests:
          - not_null
          - unique
      - name: medical_condition
      - name: test_result
        tests:
          - accepted_values:
              values: ['Abnormal', 'Inconclusive', 'Normal']
      - name: medication